apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  serviceName: "wazuh-manager"
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      containers:
      - name: wazuh-manager
        image: wazuh/wazuh-manager:4.11.2
        ports:
        - containerPort: 1514
        - containerPort: 1515
        volumeMounts:
        - name: wazuh-manager-data
          mountPath: /var/ossec/data
        - name: manager-certs
          mountPath: /etc/wazuh-manager/certs
          readOnly: true
      volumes:
      - name: wazuh-manager-data
        persistentVolumeClaim:
          claimName: wazuh-manager-pvc
      - name: manager-certs
        secret:
          secretName: manager-certs-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-pvc
  namespace: wazuh
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: azure-blob-storage-wazuh
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-indexer
  serviceName: "wazuh-indexer"
  template:
    metadata:
      labels:
        app: wazuh-indexer
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /usr/share/wazuh-indexer/data"]
        volumeMounts:
        - name: wazuh-indexer-data
          mountPath: /usr/share/wazuh-indexer/data
      - name: fix-indexer-cert-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 644 /etc/wazuh-indexer/certs"]
        volumeMounts:
        - name: indexer-certs
          mountPath: /etc/wazuh-indexer/certs
      containers:
      - name: wazuh-indexer
        image: wazuh/wazuh-indexer:4.11.2
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: wazuh-indexer-data
          mountPath: /usr/share/wazuh-indexer/data
        - name: indexer-certs
          mountPath: /etc/wazuh-indexer/certs
          readOnly: false
      volumes:
      - name: wazuh-indexer-data
        persistentVolumeClaim:
          claimName: wazuh-indexer-pvc
      - name: indexer-certs
        secret:
          secretName: indexer-certs-secret
          items:
          - key: indexer-key.pem
            path: indexer-key.pem
          - key: indexer-cert.pem
            path: indexer-cert.pem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer-pvc
  namespace: wazuh
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: azure-blob-storage-wazuh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-dashboard
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-dashboard
  template:
    metadata:
      labels:
        app: wazuh-dashboard
    spec:
      containers:
      - name: wazuh-dashboard
        image: wazuh/wazuh-dashboard:4.11.2
        ports:
        - containerPort: 443
        env:
        - name: WAZUH_DASHBOARD_SSL_ENABLED
          value: "false"
        volumeMounts:
        - name: dashboard-certs
          mountPath: /etc/wazuh-dashboard/certs
          readOnly: true
      volumes:
      - name: dashboard-certs
        secret:
          secretName: dashboard-certs-secret
          items:
          - key: dashboard-key.pem
            path: dashboard-key.pem
          - key: dashboard-cert.pem
            path: dashboard-cert.pem
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-blob-storage-wazuh
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-blob-storage-wazuh
  azureFile:
    secretName: azure-storage-secret
    shareName: wazuh-share
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: azure-blob-storage-wazuh
