name: CI/CD for Wazuh on AKS

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME_DOCKERHUB }}
        password: ${{ secrets.PAT_DOCKERHUB }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          ${{ secrets.USERNAME_DOCKERHUB }}/wazuh:latest
          ${{ secrets.USERNAME_DOCKERHUB }}/wazuh:${{ github.sha }}

  CD:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: k8s Set Context
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        Kubeconfig: ${{secrets.K8S_CONFIG}}

    - name: Deploy Kubernets cluster
      uses: Azure/k8s-deploy@v4.9
      with:
          images: samukasouza2207/wazuh:${{github.run_number}}
          manifests: |
            k8s/deployment.yaml
