name: CI/CD for Wazuh on AKS

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME_DOCKERHUB_WAZUH }}
        password: ${{ secrets.PAT_DOCKERHUB_WAZUH }}

    - name: Generate SSL Certificates
      run: bash k8s/generate_certs.sh

    - name: k8s Set Context
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        Kubeconfig: ${{secrets.K8S_CONFIG}}

    - name: Create Kubernetes Secrets for Certificates
      run: |
        kubectl create secret generic manager-certs-secret --from-file=k8s/certs/manager -n wazuh
        kubectl create secret generic indexer-certs-secret --from-file=k8s/certs/indexer -n wazuh
        kubectl create secret generic dashboard-certs-secret --from-file=k8s/certs/dashboard -n wazuh

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          ${{ secrets.USERNAME_DOCKERHUB_WAZUH }}/wazuh:latest
          ${{ secrets.USERNAME_DOCKERHUB_WAZUH }}/wazuh:${{github.run_number}}

  CD:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: k8s Set Context
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        Kubeconfig: ${{secrets.K8S_CONFIG}}

    - name: Deploy Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
          images: samukasouza2207/wazuh:${{github.run_number}}
          manifests: |
            ./k8s/wazuh-deployment.yaml
          namespace: wazuh
